### ISSUE TITLE
Dragging window issue + Crashing

### ISSUE THREAD

**Issue by ran-yakumo-eee** [FireCubeStudios/Run#10]
Yeah the title pretty much explained what's going on. This is what i'm having to dealt with:
(Windows 11 Beta 22621.674)

https://user-images.githubusercontent.com/84310373/197344531-c81ce660-377e-4753-8fe8-0a2dcd81b83b.mp4

https://user-images.githubusercontent.com/84310373/197344539-d3bd0268-d00f-4705-b906-00ff8005b5b4.mp4

**Comment by ElitePheonix2009** [comment]
1) Same dragging issue. 
2) But for me it's not crashing, but as soon as I enter something which is not a command, it shows the red line, and when I enter something which is a correct command, it runs the command even if I have not pressed the enter key. It's only happening on compact theme.
3) I also have the same issue that if I open it with the keyboard shortcut, it open multiple windows.
I'm on Windows 10 Pro 21H2 build 19044.2130

**Comment by FireCubeStudios** [comment]
The dragging issue is going to be resolved I have found a bug fix.

**Comment by FireCubeStudios** [comment]
Fixed all issues but dragging

**Comment by FireCubeStudios** [comment]
fixed
