### ISSUE TITLE
"Start using app" does nothing + other

### ISSUE THREAD

**Issue by ItzPeto** [FireCubeStudios/Run#20]
![Run-ItzPeto-03-07-2023-17-19-20](https://github.com/FireCubeStudios/Run/assets/46417703/2e83d029-3522-4b5f-a652-8e6067f8359e)
Here's the introduction window getting stuck

If I decide to close the introduction window and try to relaunch the app, it starts in the background but crashes after 2-3 seconds.

**Comment by ItzPeto** [comment]
![image](https://github.com/FireCubeStudios/Run/assets/46417703/6e42d2df-c7be-4a66-92ee-5ac0c99ceaaf)
Additional info about the crash

**Comment by FireCubeStudios** [comment]
Fixed
