### ISSUE TITLE
Please don't have people install a custom root certificate

### ISSUE THREAD

**Issue by GurliGebis** [FireCubeStudios/Run#23]
It is a really bad practice to install custom root certificates, unless it is on a test machine or from somewhere you really trust.
Doing this will allow anything signed with that certificate to be trusted by the entire system.

Telling people to install from the store is the way to go.
If not, have them generate their own certificate and sign it with that - or use a trusted code signing certificate to sign the msix package, so people don't have to trust a custom root certificate.

**Comment by FireCubeStudios** [comment]
That's just the way sidoading works. Anyway a store release is out and preferred so I'm closing this issue
